pdg:
  autoload: '../../../vendor/autoload.php'
  references:
    src: '../src'
    namespace: 'ApiPlatform'
    exclude: ['*Factory.php']
    class_tags_to_ignore: ['@experimental', '@internal', '@ignore']
    output: 'pages/references'
    base_url: '/pages/references'
  guides:
    src: 'guides'
    output: 'pages/guides'
    base_url: '/pages/guides'
